### ISSUE TITLE
Inicializar proyecto en NEXT.JS

### ISSUE THREAD

**Issue by LucasAMoralesRomero** [No-Country-simulation/c21-70-n-node-react#2]

**Comment by julianandrescaracas0623** [comment]
Miercoles no me habia visto las ramas del repo, no vi que ya habian creado el proyecto en otra rama, y lo cree en el main, pero veo que el otro no tiene la src

**Comment by nohayproblema** [comment]
cierro mi pull request y seguimos desde main. `next-skeleton` igual se suponía se mezclaría en `main`. 🚀
